FROM n8nio/n8n

ENV N8N_BASIC_AUTH_ACTIVE=true
ENV N8N_BASIC_AUTH_USER=$N8N_BASIC_AUTH_USER
ENV N8N_BASIC_AUTH_PASSWORD=$N8N_BASIC_AUTH_PASSWORD
ENV WEBHOOK_TUNNEL_URL=$WEBHOOK_TUNNEL_URL

EXPOSE 5678

CMD ["n8n"]
